package mime

// MIME type prefix register
var RegPrefix = map[Prefix]struct{}{
	Standard: {},
	Private:  {},
	Vanity:   {},
	Vendor:   {},
}

// MIME type suffix register
var RegSuffix = map[Suffix]struct{}{
	Ber:     {},
	CBor:    {},
	CBorSeq: {},
	Der:     {},
	FIS:     {},
	Json:    {},
	JsonSeq: {},
	Xml:     {},
	Wbxml:   {},
	Zip:     {},
	GZip:    {},
}

// MIME type register
var RegTypes = map[Type]struct{}{
	Audio:       {},
	Application: {},
	Chemical:    {},
	Example:     {},
	Font:        {},
	Image:       {},
	Message:     {},
	Multipart:   {},
	Text:        {},
	Video:       {},
}

// currently only for mapping/lookup, do not move entries!
var _regMime = []*MIME{
	MustParse("audio/3gpp"), MustParse("video/3gpp"),
	MustParse("audio/3gpp2"), MustParse("video/3gpp2"),
	MustParse("application/x-7z-compressed"),
	MustParse("audio/aac"),
	MustParse("application/x-abiword"),
	MustParse("application/x-freearc"),
	MustParse("image/avif"),
	MustParse("video/x-msvideo"),
	MustParse("application/vnd.amazon.ebook"),
	MustParse("application/octet-stream"),
	MustParse("image/bmp"),
	MustParse("application/x-bzip"),
	MustParse("application/x-bzip2"),
	MustParse("application/x-cdf"),
	MustParse("application/x-csh"),
	MustParse("text/css"),
	MustParse("text/csv"),
	MustParse("application/msword"),
	MustParse("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
	MustParse("application/vnd.ms-fontobject"),
	MustParse("application/epub+zip"),
	MustParse("application/gzip"),
	MustParse("image/gif"),
	MustParse("text/html"),
	MustParse("text/html"),
	MustParse("image/vnd.microsoft.icon"),
	MustParse("text/calendar"),
	MustParse("application/java-archive"),
	MustParse("image/jpeg"),
	MustParse("image/jpeg"),
	MustParse("application/json"),
	MustParse("application/ld+json"),
	MustParse("audio/midi"), MustParse("audio/x-midi"),
	MustParse("audio/midi"), MustParse("audio/x-midi"),
	MustParse("text/javascript"),
	MustParse("audio/mpeg"),
	MustParse("video/mp4"),
	MustParse("video/mpeg"),
	MustParse("application/vnd.apple.installer+xml"),
	MustParse("application/vnd.oasis.opendocument.presentation"),
	MustParse("application/vnd.oasis.opendocument.spreadsheet"),
	MustParse("application/vnd.oasis.opendocument.text"),
	MustParse("audio/ogg"),
	MustParse("video/ogg"),
	MustParse("application/ogg"),
	MustParse("audio/opus"),
	MustParse("font/otf"),
	MustParse("image/png"),
	MustParse("application/pdf"),
	MustParse("application/x-httpd-php"),
	MustParse("application/vnd.ms-powerpoint"),
	MustParse("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
	MustParse("application/vnd.rar"),
	MustParse("application/rtf"),
	MustParse("application/x-sh"),
	MustParse("image/svg+xml"),
	MustParse("application/x-tar"),
	MustParse("image/tiff"),
	MustParse("image/tiff"),
	MustParse("video/mp2t"),
	MustParse("font/ttf"),
	MustParse("text/plain"),
	MustParse("application/vnd.visio"),
	MustParse("audio/wav"),
	MustParse("audio/webm"),
	MustParse("video/webm"),
	MustParse("image/webp"),
	MustParse("font/woff"),
	MustParse("font/woff2"),
	MustParse("application/xhtml+xml"),
	MustParse("application/vnd.ms-excel"),
	MustParse("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
	MustParse("application/xml"),
	MustParse("application/vnd.mozilla.xul+xml"),
	MustParse("application/zip"),
}

// Extension / MIME mappings
var ExtMimeLookUp = map[string][]*MIME{
	".3gp":    {_regMime[0], _regMime[1]},
	".3g2":    {_regMime[2], _regMime[3]},
	".7z":     {_regMime[4]},
	".aac":    {_regMime[5]},
	".abw":    {_regMime[6]},
	".arc":    {_regMime[7]},
	".avif":   {_regMime[8]},
	".avi":    {_regMime[9]},
	".azw":    {_regMime[10]},
	".bin":    {_regMime[11]},
	".bmp":    {_regMime[12]},
	".bz":     {_regMime[13]},
	".bz2":    {_regMime[14]},
	".cda":    {_regMime[15]},
	".csh":    {_regMime[16]},
	".css":    {_regMime[17]},
	".csv":    {_regMime[18]},
	".doc":    {_regMime[19]},
	".docx":   {_regMime[20]},
	".eot":    {_regMime[21]},
	".epub":   {_regMime[22]},
	".gz":     {_regMime[23]},
	".gif":    {_regMime[24]},
	".htm":    {_regMime[25]},
	".html":   {_regMime[26]},
	".ico":    {_regMime[27]},
	".ics":    {_regMime[28]},
	".jar":    {_regMime[29]},
	".jpeg":   {_regMime[30]},
	".jpg":    {_regMime[31]},
	".json":   {_regMime[32]},
	".jsonld": {_regMime[33]},
	".mid":    {_regMime[34], _regMime[35]},
	".midi":   {_regMime[36], _regMime[37]},
	".mjs":    {_regMime[38]},
	".mp3":    {_regMime[39]},
	".mp4":    {_regMime[40]},
	".mpeg":   {_regMime[41]},
	".mpkg":   {_regMime[42]},
	".odp":    {_regMime[43]},
	".ods":    {_regMime[44]},
	".odt":    {_regMime[45]},
	".oga":    {_regMime[46]},
	".ogv":    {_regMime[47]},
	".ogx":    {_regMime[48]},
	".opus":   {_regMime[49]},
	".otf":    {_regMime[50]},
	".png":    {_regMime[51]},
	".pdf":    {_regMime[52]},
	".php":    {_regMime[53]},
	".ppt":    {_regMime[54]},
	".pptx":   {_regMime[55]},
	".rar":    {_regMime[56]},
	".rtf":    {_regMime[57]},
	".sh":     {_regMime[58]},
	".svg":    {_regMime[59]},
	".tar":    {_regMime[60]},
	".tif":    {_regMime[61]},
	".tiff":   {_regMime[62]},
	".ts":     {_regMime[63]},
	".ttf":    {_regMime[64]},
	".txt":    {_regMime[65]},
	".vsd":    {_regMime[66]},
	".wav":    {_regMime[67]},
	".weba":   {_regMime[68]},
	".webm":   {_regMime[69]},
	".webp":   {_regMime[70]},
	".woff":   {_regMime[71]},
	".woff2":  {_regMime[72]},
	".xhtml":  {_regMime[73]},
	".xls":    {_regMime[74]},
	".xlsx":   {_regMime[75]},
	".xml":    {_regMime[76]},
	".xul":    {_regMime[77]},
	".zip":    {_regMime[78]},
}
