package mime

// MIME type prefix register
var RegPrefix = map[Prefix]struct{}{
	Standard: {},
	Private:  {},
	Vanity:   {},
	Vendor:   {},
}

// MIME type suffix register
var RegSuffix = map[Suffix]struct{}{
	Ber:     {},
	CBor:    {},
	CBorSeq: {},
	Der:     {},
	FIS:     {},
	Json:    {},
	JsonSeq: {},
	Xml:     {},
	Wbxml:   {},
	Zip:     {},
	GZip:    {},
}

// MIME type register
var RegTypes = map[Type]struct{}{
	Audio:    {},
	App:      {},
	Chemical: {},
	Example:  {},
	Font:     {},
	Image:    {},
	Message:  {},
	MultiPt:  {},
	Text:     {},
	Video:    {},
}

var ExtensionMap = map[string]Variety{
	".aac":    *MustParse("audio/aac"),
	".abw":    *MustParse("application/x-abiword"),
	".arc":    *MustParse("application/x-freearc"),
	".avif":   *MustParse("image/avif"),
	".avi":    *MustParse("video/x-msvideo"),
	".azw":    *MustParse("application/vnd.amazon.ebook"),
	".bin":    *MustParse("application/octet-stream"),
	".bmp":    *MustParse("image/bmp"),
	".bz":     *MustParse("application/x-bzip"),
	".bz2":    *MustParse("application/x-bzip2"),
	".cda":    *MustParse("application/x-cdf"),
	".csh":    *MustParse("application/x-csh"),
	".css":    *MustParse("text/css"),
	".csv":    *MustParse("text/csv"),
	".doc":    *MustParse("application/msword"),
	".docx":   *MustParse("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
	".eot":    *MustParse("application/vnd.ms-fontobject"),
	".epub":   *MustParse("application/epub+zip"),
	".gz":     *MustParse("application/gzip"),
	".gif":    *MustParse("image/gif"),
	".htm":    *MustParse("text/html"),
	".html":   *MustParse("text/html"),
	".ico":    *MustParse("image/vnd.microsoft.icon"),
	".ics":    *MustParse("text/calendar"),
	".jar":    *MustParse("application/java-archive"),
	".jpeg":   *MustParse("image/jpeg"),
	".jpg":    *MustParse("image/jpeg"),
	".json":   *MustParse("application/json"),
	".jsonld": *MustParse("application/ld+json"),
	".mid":    *MustParse("audio/midi"), // TBD: also 'audio/x-midi' should map .mid
	".midi":   *MustParse("audio/midi"), // TBD: also 'audio/x-midi' should map .midi
	".mjs":    *MustParse("text/javascript"),
	".mp3":    *MustParse("audio/mpeg"),
	".mp4":    *MustParse("video/mp4"),
	".mpeg":   *MustParse("video/mpeg"),
	".mpkg":   *MustParse("application/vnd.apple.installer+xml"),
	".odp":    *MustParse("application/vnd.oasis.opendocument.presentation"),
	".ods":    *MustParse("application/vnd.oasis.opendocument.spreadsheet"),
	".odt":    *MustParse("application/vnd.oasis.opendocument.text"),
	".oga":    *MustParse("audio/ogg"),
	".ogv":    *MustParse("video/ogg"),
	".ogx":    *MustParse("application/ogg"),
	".opus":   *MustParse("audio/opus"),
	".otf":    *MustParse("font/otf"),
	".png":    *MustParse("image/png"),
	".pdf":    *MustParse("application/pdf"),
	".php":    *MustParse("application/x-httpd-php"),
	".ppt":    *MustParse("application/vnd.ms-powerpoint"),
	".pptx":   *MustParse("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
	".rar":    *MustParse("application/vnd.rar"),
	".rtf":    *MustParse("application/rtf"),
	".sh":     *MustParse("application/x-sh"),
	".svg":    *MustParse("image/svg+xml"),
	".tar":    *MustParse("application/x-tar"),
	".tif":    *MustParse("image/tiff"),
	".tiff":   *MustParse("image/tiff"),
	".ts":     *MustParse("video/mp2t"),
	".ttf":    *MustParse("font/ttf"),
	".txt":    *MustParse("text/plain"),
	".vsd":    *MustParse("application/vnd.visio"),
	".wav":    *MustParse("audio/wav"),
	".weba":   *MustParse("audio/webm"),
	".webm":   *MustParse("video/webm"),
	".webp":   *MustParse("image/webp"),
	".woff":   *MustParse("font/woff"),
	".woff2":  *MustParse("font/woff2"),
	".xhtml":  *MustParse("application/xhtml+xml"),
	".xls":    *MustParse("application/vnd.ms-excel"),
	".xlsx":   *MustParse("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
	".xml":    *MustParse("application/xml"),
	".xul":    *MustParse("application/vnd.mozilla.xul+xml"),
	".zip":    *MustParse("application/zip"),
	".3gp":    *MustParse("video/3gpp"),  // TBD: audio/3gpp if audio only
	".3g2":    *MustParse("video/3gpp2"), // TBD: audio/3gpp2 if audio only
	".7z":     *MustParse("application/x-7z-compressed"),
}
